### ISSUE TITLE
Separating the firstpass size from the SDLX one

### ISSUE THREAD

**Issue by HeavyTony2** [light-and-ray/sd-webui-old-sd-firstpasser#4]
The script use an upscaler, however, there's currently no genuine upscale process since the sizes of the first pass and the finale results are the same.

**Comment by light-and-ray** [comment]
Why there is no? Firstpass is 512p, second pass is your selected resolution. If you select 512 sdxl, so upscaling will be 1x, and ignoring automatically. But no one uses 512 for sdxl

**Comment by HeavyTony2** [comment]
Nevermind, I realized while looking to the console and the output folder there was an actual upscaling process. On the other hand, it could be a good idea to be able to customise the size of the SD 1.5 firstpass.

**Comment by light-and-ray** [comment]
I thing it would have been over complicated if id added. The less number of options is better for this kind of extension

**Comment by HeavyTony2** [comment]
> I thing it would have been over complicated if id added. The less number of options is better for this kind of extension

I disagree, but you're the developper after all. Thanks for the quick answers. It's greatly appreciated.
